In [3]:
import numpy as np

ROUND 1 - Smoking Stump

In [4]:
X = np.array([
    [38, 420000, 0],
    [52, 360000, 5],
    [45, 780000, 0],
    [29, 300000, 12],
    [61, 500000, 8]
])

#Illness (Yes = +1, No = -1)
y = np.array([-1, +1, +1, +1, +1])

#Initial Weights
w = np.ones(len(y)) / len(y)

In [5]:
print(w)

[0.2 0.2 0.2 0.2 0.2]


In [6]:
def stump_on_smoking(x):
  return 1 if x[2] >= 1 else -1

In [7]:
h1 = []
for row in X:
    h1.append(stump_on_smoking(row))
print(h1)

[-1, 1, -1, 1, 1]


In [8]:
def weighted_error(y, preds, w):
    return np.sum(w[y != preds])

preds = h1
error = weighted_error(y, preds, w)
print(error)

0.2


In [9]:
def compute_alpha(error):
    return 0.5 * np.log((1 - error) / error)

alpha = compute_alpha(error)
print(alpha)

0.6931471805599453


In [10]:
def update_weights(w, alpha, y, preds):
  w_new = w * np.exp(-alpha * y * preds)
  return w_new / np.sum(w_new)

updated_weights = update_weights(w,alpha,y,preds)
print(updated_weights)

[0.125 0.125 0.5   0.125 0.125]


In [12]:
print("ROUND 1")
print("Weighted Error ε1 =", error)
print("Alpha α1 =", round(alpha, 4))
print("Updated Weights =", np.round(updated_weights, 4))
print()

ROUND 1
Weighted Error ε1 = 0.2
Alpha α1 = 0.6931
Updated Weights = [0.125 0.125 0.5   0.125 0.125]



ROUND 2 - Age Stump


In [21]:
def stump_on_age(x):
    return 1 if x[0] >= 45 else -1

In [22]:
h2 = []
for row in X:
    h2.append(stump_on_age(row))

h2 = np.array(h2)
print("Predictions h2:", h2)


Predictions h2: [-1  1  1 -1  1]


In [27]:
def weighted_error_round2(y, preds2, updated_weights):
    return np.sum(updated_weights[y != preds2])

preds2 = h2
error2 = weighted_error_round2(y, preds2, updated_weights)
print("Weighted error ε2 =", error2)


Weighted error ε2 = 0.125


In [28]:
def compute_alpha_round2(error2):
    return 0.5 * np.log((1 - error2) / error2)

alpha2 = compute_alpha_round2(error2)
print(alpha2)

0.9729550745276566


In [29]:
def update_weights_round2(updated_weights, alpha2, y, preds2):
  w_new2 = w * np.exp(-alpha2 * y * preds2)
  return w_new2 / np.sum(w_new2)

updated_weights_round2 = update_weights(updated_weights,alpha2,y,preds2)
print(updated_weights_round2)

[0.07142857 0.07142857 0.28571429 0.5        0.07142857]


In [31]:
print("ROUND 2")
print("Weighted Error ε2 =", error2)
print("Alpha α2 =", round(alpha2, 4))
print("Updated Weights =", np.round(updated_weights_round2, 4))
print()

ROUND 2
Weighted Error ε2 = 0.125
Alpha α2 = 0.973
Updated Weights = [0.0714 0.0714 0.2857 0.5    0.0714]



ROUND 3 - Smoking Stump Again

In [32]:
def stump_smoking_3(x):
  return 1 if x[2] >= 1 else -1

In [33]:
h3 = []
for row in X:
    h3.append(stump_smoking_3(row))

h3 = np.array(h3)
print("Predictions h3:", h3)


Predictions h3: [-1  1 -1  1  1]


In [35]:
def weighted_error_round3(y, preds3, updated_weights_round3):
    return np.sum(updated_weights_round2[y != preds3])

preds3 = h3
error3 = weighted_error_round3(y, preds3, updated_weights_round2)
print("Weighted error ε2 =", error3)


Weighted error ε2 = 0.28571428571428575


In [36]:
def compute_alpha_round3(error3):
    return 0.5 * np.log((1 - error3) / error3)

alpha3 = compute_alpha_round3(error3)
print(alpha3)

0.45814536593707733


In [38]:
print("ROUND 3")
print("Weighted Error ε3 =", round(error3, 4))
print("Alpha α3 =", round(alpha3, 4))
print()

ROUND 3
Weighted Error ε3 = 0.2857
Alpha α3 = 0.4581



FINAL CLASS CLASSIFIER

In [41]:
# Make sure predictions are numpy arrays
preds  = np.array(preds)
preds2 = np.array(preds2)
preds3 = np.array(preds3)

# Final score (weighted sum)
final_score = (
    alpha  * preds +
    alpha2 * preds2 +
    alpha3 * preds3
)

# Final prediction
final_prediction = np.sign(final_score)

print("FINAL STRONG CLASSIFIER RESULTS")
for i in range(len(y)):
    print(
        f"Row {i+1}: "
        f"Score = {final_score[i]:.4f}, "
        f"Prediction = {int(final_prediction[i])}, "
        f"True y = {y[i]}"
    )


FINAL STRONG CLASSIFIER RESULTS
Row 1: Score = -2.1242, Prediction = -1, True y = -1
Row 2: Score = 2.1242, Prediction = 1, True y = 1
Row 3: Score = 1.2080, Prediction = 1, True y = 1
Row 4: Score = -1.2080, Prediction = -1, True y = 1
Row 5: Score = 2.1242, Prediction = 1, True y = 1
